#!/bin/bash
 
source $HOME/Media/Code/rofi/rofi_vars


query=$(rofi -dmenu -i -p "Busca en el diccionario" -font 'Comic Mono 18' -theme "$theme" -show-icons -lines 0 -no-fixed-num-lines)

results=$(grep -i "^$query" "/home/clyde/Media/PDF and Books/diccionario/diccionario.txt" | sed G)

if [ -n "$query" ]; then
    rofi -font 'Comic Mono 18' -theme "$theme" -e "$results"
fi
