#!/bin/bash

query=$(rofi -dmenu -i -p "Busca en el diccionario" -font 'Comic Mono 18' -theme glue_pro_blue -show-icons -lines 0 -no-fixed-num-lines)

results=$(grep -i "^$query" "/home/clyde/Media/PDF and Books/diccionario/diccionario.txt" | sed G)

if [ -n "$query" ]; then
    rofi -font 'Comic Mono 18' -theme glue_pro_blue -e "$results"
fi
