#!/bin/bash
 
source $HOME/Media/Code/rofi/rofi_vars


selected_file="/home/clyde/Media/PDF and Books/Oxford English Dictionary.txt"

if [ -n "$selected_file" ]; then
    file_path="$selected_file"
    
    file_content=$(grep -v '^$' "$file_path" | rofi -matching regex -font 'Comic Mono 18' -theme "$theme" -dmenu -i -p "Search in dictionary" -mesg "")
    
    if [ -n "$file_content" ]; then
        rofi -font 'Comic Mono 18' -theme "$theme" -e "$file_content"

        echo -n "$file_content" | xclip -selection clipboard
    fi
fi
