#!/bin/bash
 
source $HOME/Media/Code/rofi/rofi_vars


options="exit i3\npoweroff\nreboot\ncancel"
response=$(echo -e "$options" | rofi -dmenu -p "Select an option:" -font 'Comic Mono 18' -theme "$theme")

case "$response" in
    "exit i3")
        i3-msg exit
        ;;
    "poweroff")
        sudo shutdown now
        ;;
    "reboot")
        reboot
        ;;
    "cancel")
        ;;
esac
