#!/bin/bash
 
source $HOME/Media/Code/rofi/rofi_vars


#  IMPORTANT: this program asumes you have your passwords
#  stored in this format:
#
#  decription-username
#
#  like, for example:
#  twitter-johnwick3
#  facebook-longAnd_complicated-username123
#  
#  this is to ensure you can store such information, and not
#  have to remember it. if you don't like the format, i'm
#  sorry, you may change the script below

password_store_dir="$HOME/.password-store/"

if [ ! -d "$password_store_dir" ]; then
    rofi -e "Password store directory not found: $password_store_dir"
    exit 1
fi

selected_entry=$(ls "$password_store_dir" | rev | cut -c 5- | rev | rofi -font 'Comic Mono 18' -theme "$theme" -dmenu -p "Select pass entry:")

if [ -z "$selected_entry" ]; then
    echo "Entry selection canceled."
    exit 0
fi

options=(
"entry name paste macro
password paste macro
copy password to clipboard
autotype password
autotype entry name")

selected_option=$(rofi -font 'Comic Mono 18' -theme "$theme" -dmenu -p "Select an option for $selected_entry:" <<< "${options[@]}")

if [ -z "$selected_option" ]; then
    echo "Option selection canceled."
    exit 0
fi

case "$selected_option" in
    "autotype entry name")
        echo "$selected_entry" | sed 's/^.*-//' | xdotool type --clearmodifiers --delay 8 --file -
        ;;
    "entry name paste macro")
        echo "$selected_entry" | sed 's/^.*-//' | xclip -sel c && xdotool key ctrl+shift+v
        ;;
    "autotype password")
        echo "$selected_entry"
        pass "$selected_entry" | xdotool type --clearmodifiers --delay 50 --file -
        ;;
    "password paste macro")
        pass "$selected_entry" | tr -d '\n' | xclip -sel c && xdotool key ctrl+shift+v
        ;;
    "copy password to clipboard")
        pass "$selected_entry" | xclip -sel c
        ;;
    "entry name copy and paste macro")
        echo "$selected_entry" | sed 's/^.*-//' | tr -d '\n' | xclip -sel c && xdotool key ctrl+shift+v
        ;;
    *)
        echo "Invalid option selected."
        ;;
esac

exit 0
