#!/bin/bash
 
source $HOME/Media/Code/rofi/rofi_vars


#  IMPORTANT: this program asumes you have your passwords
#  stored in this format:
#
#  decription-username
#
#  like, for example:
#  twitter-johnwick3
#  facebook-longAnd_complicated-username123
#  
#  this is to ensure you can store such information, and not
#  have to remember it. if you don't like the format, i'm
#  sorry, you may change the script below

export PASSWORD_STORE_DIR="$HOME/Media/Sensible/pass/password-store/"

if [ ! -d "$PASSWORD_STORE_DIR" ]; then
    rofi -font "$font" -theme "$theme" -e "Password store directory not found: $password_store_dir"
    exit 1
fi

main_entries=$(ls -1l "$PASSWORD_STORE_DIR" | grep -v ^d | cut -d' ' -f9 | sed 1d | rev | cut -c 5- | rev)
otp_entries=$(ls -1 "$PASSWORD_STORE_DIR"/otp | rev | cut -c 5- | rev)

selected_entry=$(echo -e "$main_entries\n$otp_entries" | rofi -font "$font" -theme "$theme" -dmenu -p "Select pass entry")

if [ -z "$selected_entry" ]; then
    echo "Entry selection canceled."
    exit 0
fi

options=(
"entry name paste macro
password paste macro
copy password to clipboard
autotype password
autotype entry name")

selected_option=$(rofi -font "$font" -theme "$theme" -dmenu -p "Select an option for $selected_entry" <<< "${options[@]}")

if [ -z "$selected_option" ]; then
    echo "Option selection canceled."
    exit 0
fi

case "$selected_option" in
    "entry name paste macro")
        echo "$selected_entry" | sed 's/^.*-//' | tr -d '\n' | xclip -sel c && xdotool key ctrl+shift+v
        ;;
    "password paste macro")
        { pass "$selected_entry" || pass otp otp/"$selected_entry"; } | tr -d '\n' | xclip -sel c && xdotool key ctrl+shift+v
        ;;
    "copy password to clipboard")
       { pass "$selected_entry" || pass otp otp/"$selected_entry"; } | tr -d '\n' | xclip -sel c & sleep 10 && echo "" | xclip -sel c
        ;;
    "autotype password")
        echo "$selected_entry"
        { pass "$selected_entry" || pass otp otp/"$selected_entry"; } | xdotool type --clearmodifiers --delay 50 --file -
        ;;
    "entry name copy and paste macro")
        echo "$selected_entry" | tr -d '\n' | sed 's/^.*-//' | tr -d '\n' | xclip -sel c && xdotool key ctrl+shift+v
        ;;
    "autotype entry name")
        echo "$selected_entry" | sed 's/^.*-//' | tr -d '\n'| xdotool type --clearmodifiers --delay 8 --file -
        ;;
esac

exit 0

