#!/bin/bash
 
source $HOME/Media/Code/rofi/rofi_vars


query=$(rofi -dmenu -i -p "Translate" -font 'Comic Mono 18' -theme "$theme" -show-icons -lines 0 -no-fixed-num-lines)

if [ -n "$query" ]; then
    waterfox "https://translate.google.es/?sl=auto&tl=es&text=$query" &
fi
